# `sudo:false` for faster builds.
sudo: false
language: node_js
cache:
  directories:
    - "node_modules"

# env forces jobs to be created from the top level settings
env:
jobs:
  include:
    - stage: moban
      language: python
      python: 3.6
      cache: pip
      before_install: false
      install: pip install moban
      before_script: false
      script: .ci/check_moban.sh
      after_success: false
      deploy: false

# Needed for Firefox
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

before_install:
  - npm install --no-save --no-optional --only=dev npm@5.8.0

install:
  - npm install --no-save --no-optional

before_install:
  # bufferstream in package-lock.json means optional dependencies
  # have been included.
  - if grep bufferstream package-lock.json ; then false; fi

script:
  - script/build.sh
  - npm run test

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

# Remove /dist/ from .gitignore
before_deploy:
  - sed -i '/dist\//d' ./.gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
